### ISSUE TITLE
Later - relaunch Rater manually before the launch time out.

### ISSUE THREAD

**Issue by mahekmshah** [delight-im/AppRater#10]
This is a good library, however I am seeing a small issue.

If I do Later and then I decide no I want to rate now then the dialog is not shown unless the launch time of I guess 2days is up. 
NOTE: I am doing setDaysBeforePrompt(0); and setLaunchesBeforePrompt(0) before calling show, everytime user clicks on rate us.

Is this a bug or am I doing something incorrect. Please suggest.

My guess is this would be the same behavior for Never also, though IMO never means never prompt me but the user can choose to rate whenever he/she wants to. Maybe this can be an additional configuration, if we want to override the user's previous selection of Never.

Thanks!

**Comment by ocram** [comment]
Thanks, let's debug this!

> If I do Later and then I decide no I want to rate now then the dialog is not shown unless the launch time of I guess 2days is up.

Yes, because when the user says "later", they obviously don't want to see it immediately again. The only reasonable thing that might be changed is the interval between choosing "later" and the dialog appearing again. This proposed change is tracked in https://github.com/delight-im/AppRater/issues/6.

> Is this a bug or am I doing something incorrect. Please suggest.

Neither, I'd say. See above.

> My guess is this would be the same behavior for Never also

No. "Never" really means "ask me never again", while "later" means "wait some time and then please ask me again". This makes sense, doesn't it?

> IMO never means never prompt me but the user can choose to rate whenever he/she wants to

Of course, the user may choose to rate the app via some other way at their own discretion, at any time. But the dialog, which this library is about, will indeed appear _never again_.

> Maybe this can be an additional configuration, if we want to override the user's previous selection of Never.

I don't think that makes any sense. Sorry! "Never" really means never. But perhaps the other changed (see above) is what you're actually caring about.

Hope that helps!

**Comment by mahekmshah** [comment]
thanks @ocram
